import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FloatinNavBar from "@/components/FloatingNavBar";
import Header from "@/components/Header";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout function component.
 *
 * Renders the root layout of the application, including a floating navigation bar, header, and children components.
 *
 * @param children - The child components to be rendered within the layout.
 * @returns The root layout of the application with the specified child components.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <FloatinNavBar />
        <Header />
        <div id="top" className="sr-only">
          <Link href="#main"> skip to main cotent</Link>
        </div>
        <main className="relative" id="main">
          {children}
        </main>
      </body>
    </html>
  );
}
